### ISSUE TITLE
ArgumentPart suggestions

### ISSUE THREAD

**Issue by pixeldev** [unnamed/command-flow#20]
Well, I think there's a issue with part suggestions in sub-commands, if we have a empty parent sub-command then the next argument position wouldn't be suggested correctly.

There is an example, as you can see we have a empty parent with a custom part called 'Bank'. Suggestions of that part aren't being suggested, but this issue only occurs with the empty parent.

![image](https://user-images.githubusercontent.com/56179468/151635964-c73058fc-c342-4502-848a-f77e0e630821.png)

![image](https://user-images.githubusercontent.com/56179468/151636042-dd027cf4-48b0-40b3-b4d1-7b55f76bcabf.png)

**Comment by FixedDev** [comment]
It isn't related with the actual parts, the problem is with the FirstMatchPart.
